# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Region name')),
            ],
            options={
                'verbose_name_plural': 'Data Regions',
                'verbose_name': 'Data Region',
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256, verbose_name='Country')),
                ('value', models.IntegerField(max_length=256, verbose_name='Value')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.DataRegion')),
            ],
            options={
                'verbose_name_plural': 'Data Values',
                'verbose_name': 'Data Value',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/', verbose_name='File')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Adding date')),
            ],
        ),
    ]
